PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 220
PLAYER_SPEED = 1

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# COLORS
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)


ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.6  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 0.8
PLAYER_SHOOT_COOLDOWN = 60